### ISSUE TITLE
Realiseer een 'vind'-functie

### ISSUE THREAD

**Issue by lync0001** [lync0001/biep_online#7]
Zorg ervoor dat gebruikers boeken kunnen vinden (zoeken).

**Comment by huib0029** [comment]
User Storie, boeken vinden door scholieren
Als scholier wil ik ook zelf (snel) boeken kunnen vinden op de computer zonder dat ik daarvoor iets hoef te vragen aan de bibliothecaris/ bibliothecaresse zodat het tijd scheelt. 
Bijbehorende AC’s:

-	Interface moet simpel en snel zijn
-	Interface moet overzichtelijk zijn
-	Connectie met controller en Database moet gecreëerd worden

**Comment by lync0001** [comment]
Interface gerealiseerd, overzichtelijk. De connectie is gemaakt met een database. Deze connectie werkt, maar kan beter. Nieuwe issue hierover spoedig.
